### ISSUE TITLE
Background touchable

### ISSUE THREAD

**Issue by ebarahona** [hamidhadi/react-native-stretchy#23]
Hi, great parallax scroll!

Is there a way to make the background touchable?  I understand the foreground can be touchable but the background parallax effect is more elegant.  I was able to render a component by passing it as a "header" prop and changed the image animated background type (see below) but I'm still unable to get touch events firing, Is there a way to make the background touchable?

animatedImageBackground.js:
import { Animated, TouchableOpacity } from 'react-native';
export const AnimatedImageBackground = Animated.createAnimatedComponent(TouchableOpacity);

**Comment by hamidhadi** [comment]
Thanks @ebarahona,
As you said, you can use anything you want as your foreground component. I can't understand what's the difference between making foreground or background touchable for you. 🤔
The behavior is the same!
Also, foreground component will be placed on top of the background so the background component doesn't catch any touch event. That's why you couldn't do that by changing `animatedImageBackground.js` 🙂

**Comment by ebarahona** [comment]
The effect is a bit different, the background has more of a fixed feel, I’m currently trying to resolve this with pan responder ref
